# Generated by Django 4.2.3 on 2023-07-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0002_restaurant_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=10,
            ),
        ),
    ]
