# Generated by Django 4.2.3 on 2023-08-02 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0003_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
