# Generated by Django 4.2.3 on 2023-08-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0008_alter_customuser_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
