# Generated by Django 4.2.3 on 2023-08-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0009_remove_customuser_contact_remove_customuser_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="contact",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=10,
            ),
        ),
    ]
