# Generated by Django 4.2.3 on 2023-08-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0010_customuser_contact_customuser_email_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_login",
            field=models.BooleanField(default=False),
        ),
    ]
