# Generated by Django 4.2.3 on 2023-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0011_customuser_is_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
