# Generated by Django 4.2.3 on 2023-08-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0012_customuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
