# Generated by Django 4.2.3 on 2023-08-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0013_food_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=10,
            ),
        ),
    ]
