# Generated by Django 4.2.3 on 2023-08-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0014_remove_customuser_is_admin_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
