# Generated by Django 4.2.3 on 2023-08-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0015_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default="", max_length=100, unique=True),
        ),
    ]
